---

- name: NEXUS | Update admin password
  import_tasks: ../../script/run_script.yml
  vars:
    script_name: security_admin_password
    args:
      new_password: "{{ nexus_admin_password }}"

- name: NEXUS | Actual admin password changed
  set_fact:
    current_nexus_admin_password: "{{ nexus_admin_password }}"
  no_log: true
