---
#requirements install 
- name: Install Roles from Galxy
  hosts: jenkins
  tasks:
          - name: install required ansible-galaxy roles
            command: "ansible-galaxy install --ignore-errors -r requirements.yml"
  
  roles:
          - geerlingguy.java
          - geerlingguy.jenkins 
