# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
   require 'yaml'
   current_dir = File.dirname(File.expand_path(__FILE__))
   configs = YAML.load_file("#{current_dir}/config.yaml")
   vagrant_config = configs['configs'][configs['configs']['use']]

# config.vm.define "VAGRANT_NAME" do |VAGRANT_NAME|
  config.vm.box =  vagrant_config['box_name']
  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", ip:  vagrant_config ['ip_addr']
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  config.vm.provision "shell", path: "./test.sh"
end
