---
nexus_blob_prefix: blob- # Note: Nexus restore - blob name-convention 'blob-*'
nexus_blob_mvn: "{{ nexus_blob_prefix }}mvn"
nexus_blob_docker: "{{ nexus_blob_prefix }}docker"
nexus_blob_npm: "{{ nexus_blob_prefix }}npm"
nexus_blob_nuget: "{{ nexus_blob_prefix }}nuget"
nexus_blob_pypi: "{{ nexus_blob_prefix }}pypi"
nexus_blob_raw: "{{ nexus_blob_prefix }}raw"

nexus_blobstores:
  - name: "{{ nexus_blob_prefix }}mvn"
    path: "{{ nexus_data_path }}/blobs/{{ nexus_blob_mvn }}"
  - name: "{{ nexus_blob_prefix }}docker"
    path: "{{ nexus_data_path }}/blobs/{{ nexus_blob_docker }}"
  - name: "{{ nexus_blob_prefix }}npm"
    path: "{{ nexus_data_path }}/blobs/{{ nexus_blob_npm }}"
  - name: "{{ nexus_blob_prefix }}nuget"
    path: "{{ nexus_data_path }}/blobs/{{ nexus_blob_nuget }}"
  - name: "{{ nexus_blob_prefix }}pypi"
    path: "{{ nexus_data_path }}/blobs/{{ nexus_blob_pypi }}"
  - name: "{{ nexus_blob_prefix }}raw"
    path: "{{ nexus_data_path }}/blobs/{{ nexus_blob_raw }}"
